version: '3.9'
services:
  node:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: re-jsperf
    ports:
      - 3000:3000
    volumes:
      - ./front/:/home/app
      - node_modules_volume:/home/app/node_modules:delegated
      - build_volume:/home/app/.next:nocopy

volumes:
  node_modules_volume:
  build_volume:
